name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  types:
    name: Types
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/install-node-pnpm
    - run: pnpm run typecheck

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/install-node-pnpm
    - run: pnpm run lint

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/install-node-pnpm
    - run: pnpm run format

  test:
    name: Tests (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version:
          - 21
          - 20
          - 18
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-node-pnpm
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run unit tests
        run: pnpm run test
